### ISSUE TITLE
Can't Work with ION SETUP or /dev/ttyO2

### ISSUE THREAD

**Issue by cevatbostancioglu** [3cky/mbusd#10]
Hello , i am using ION Setup program for read devices. i am also trying to make rtu/tcp gateway with my custom emb linux board. when i try to read devices with ION Setup program , just nothing happens. 

so dou you have any idea ? 

![image](https://cloud.githubusercontent.com/assets/6525009/20563579/dd12b57a-b191-11e6-807d-7b9ab83dcd52.png)

**Comment by 3cky** [comment]
It looks like ION Setup program prematurely closes connection before request has been completed. Could you try to issue same read request using a different Modbus/TCP client?
