### ISSUE TITLE
.deb installation for aarch64

### ISSUE THREAD

**Issue by rubenvanwanzeele** [3cky/mbusd#110]
Hi there,

I would need a .deb installation file for aarch64 for mbusd, but I currently fail to create one. Can you guide me on how this can be done?

**Comment by zmata** [comment]
Hi, you need to use checkinstall command

**Comment by rubenvanwanzeele** [comment]
@zmata that worked, thx, but still struggling to resolve the issue on your repo...

**Comment by 3cky** [comment]
> Hi there,
> 
> I would need a .deb installation file for aarch64 for mbusd, but I currently fail to create one. Can you guide me on how this can be done?

On your aarch64 machine, try to execute the following commands in `mbusd` sources directory:
```
mkdir ./build
cd ./build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make all
cpack -G DEB
```
After that, the generated .deb file should be placed in `build` directory.
