### ISSUE TITLE
Inversed register order

### ISSUE THREAD

**Issue by jonastim** [3cky/mbusd#15]
It seems that mbusd changes the register order for multi-register requests from what [modpoll](http://www.modbusdriver.com/modpoll.html) reads directly from RTU.

Modpoll reads 16bit (-t 4 flag) as
register 57734: 6
register 57735: 0

32bit (-t:int flag) as
register 57734: 6

inversed register 32bit (-t:int -i flags) "Slave operates on big-endian 32-bit integers"
register 57734: 393216

With mbusd reading single registers results in the same values as with modpoll, but reading a 32bit word from register 57734 results in the register inversed value 393216.

Is there a way to retain the original register order / inverse the current order?

**Comment by nickma82** [comment]
Isn't this a philosophy question (intel vs motorla) 
https://m.control.com/thread/1026161289 ?
