### ISSUE TITLE
does mbusd support RS422

### ISSUE THREAD

**Issue by shaotangyu** [3cky/mbusd#17]
Hi,

The introduction of mbusd mentioned it is RS232/RS485 Modbus Gateway.
Because RS485 and RS422 are a little different in half-duplex and full-duplex, does mbusd also have RS422 Modbus Gateway function ? 

Regards,
shaotang

**Comment by 3cky** [comment]
Hi shaotang,

As  full-duplex RS422 interface could be treated as long-range RS-232, so (theoretically) mbusd should work fine with RS422.

**Comment by nickma82** [comment]
@shaotangyu any practical results?
If yes, please share them and close the ticket...

**Comment by shaotangyu** [comment]
Yes, it can be treated as RS-232, and it works according to my test.
