### ISSUE TITLE
questions about the parameters

### ISSUE THREAD

**Issue by shaotangyu** [3cky/mbusd#19]
Hi Expert,

Could we ask some questions about the parameters provided ? 
The testbed should be as below.
PC(Modbus Client)---------DUT(Modbus Server-Modbus Gateway-Modbus Master)-------Modbus Slaver

   -N retries
          Specifies maximum number of request retries (0 disables retries).
==> does this parameters for the interface between DUT and Modbus Slaver, and if request sent to Modbus slaver fail or timeout, it will retry?

   -R pause
          Specifies pause between requests in milliseconds.
==> The request is from PC(Modbus Client) to Modbus Slaver device. Does it mean the codebase can add some milliseconds when DUT receive request from PC, and then send to Modbus Slaver ?

   -W wait
          Specifies response wait time in milliseconds.
==> Does this parameters for TCP connection between PC and DUT? 
Does it mean wait time for each Modbus command?
 
   -T timeout
          Specifies connection timeout value in seconds (0 disables timeout).
==> Does this parameters for TCP connection between PC and DUT? 
TCP connection timeout socket parameter.

Regards,
shaotang

**Comment by 3cky** [comment]
Hi shaotangyu, yes, you got that right, except `wait` parameter that is actually applied to DUT-Slave request.
