### ISSUE TITLE
-m option not documented in mbusd's man page

### ISSUE THREAD

**Issue by mbs38** [3cky/mbusd#4]
Hi,
I was looking for a configuration option for serial parity bits and only found it in the source code. Maybe it should be added to the man page as well.

Best regards & thanks for the good work

**Comment by 3cky** [comment]
Hmm, but `-m` option description should be already present in man page: https://github.com/3cky/mbusd/blob/master/doc/mbusd.8.in#L52-L53

Also it should be described in command help (`-h`). Could you check that mbus is compiled using latest sources?

**Comment by mbs38** [comment]
Yep. I accidently used an older version that was still sitting in my download directory. Sorry about that.
Anyway, thanks for the quick reply :)

**Comment by 3cky** [comment]
OK, no problem! :)
