### ISSUE TITLE
RTU over TCP?

### ISSUE THREAD

**Issue by nzfarmer1** [3cky/mbusd#45]
Hi,

Can I use your tool to map Modbus TCP to Modbus RTU over an IP network?

I'm using an Ethernet to Serial adaptor so can use socat to create a virtual serial port over IP, but the packet format is still RTU and socat is a little unstable through resets.

I was looking for something that proxy Modbus TCP to RTU but use an IP network (TCP or UDP)

**Comment by 3cky** [comment]
Well, since mbusd acts as a gateway translating Modbus TCP master requests to Modbus RTU RS-232/485 slaves network and back, I guess - yes, you can. :)

**Comment by nzfarmer1** [comment]
But we'd have to adapt the code (which may be a reasonable project).

It appears that using the UDP option in our RTU to Ethernet adaptor gives us stability - fingers crossed.

socat -d -d -d pty,link=${VPORT},b${BAUD},echo=0,raw,unlink-close=0 udp:${USRIOTADDR}:${USRIOTPORT},reuseaddr

**Comment by nickma82** [comment]
@nzfarmer1  Please close the ticket
