### ISSUE TITLE
Modbus RTU slave mode

### ISSUE THREAD

**Issue by j123b567** [3cky/mbusd#69]
Is it possible to run mbusd in reversed mode? So

- on one end, mbusd is TCP server as it is now, but in Modbus/TCP master mode
- on the other end, mbusd is connected to RS-485 and behaves as Modbus/RTU slave

So, basically, if there is some "dumb" mode, where mbusd just understand Modbus/RTU framing, crc and not the content and pack/unpack messages to/from TCP.

**Comment by 3cky** [comment]
Sorry, but currently mbusd acts only as a gateway from TCP to RTU network, and reverse mode is not supported.

**Comment by j123b567** [comment]
Ok, thank you.
