### ISSUE TITLE
Can't run Make, make script links to specific automake/aclocal version

### ISSUE THREAD

**Issue by Fohdeesha** [3cky/mbusd#8]
Trying to do a clean install of mbusd (cloned from git), once I get to the make step I run into the error below. This is on a clean install of the latest stable Debian (8) amd64, who's latest stable automake is 1.14.1. with aclocal 1.14.1

It is my understanding that make scripts shouldn't reference specific versions at all, for example: 
http://stackoverflow.com/a/37669184

This is the output I get when I run make on a system with the latest debian stable automake/aclocal installed, 1.14

---

root@modbus:~/mbusd.git# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /root/mbusd.git/missing aclocal-1.15 -I m4
/root/mbusd.git/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         http://www.gnu.org/software/automake
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         http://www.gnu.org/software/autoconf
         http://www.gnu.org/software/m4/
         http://www.perl.org/
Makefile:406: recipe for target 'aclocal.m4' failed
make: **\* [aclocal.m4] Error 127

---

automake version:
root@modbus:~/mbusd.git# automake --version
automake (GNU automake) 1.14.1

aclocal version:
root@modbus:~/mbusd.git# aclocal --version
aclocal (GNU automake) 1.14.1

**Comment by Fohdeesha** [comment]
I followed the steps here from anotherp roject with the same issue https://github.com/Jasig/mod_auth_cas/issues/97

I ran "autoreconf -f -i" and then I was able to fully ./configure, make, and make install, and now it is working as expected. It seems it's related to cloning from git as timestamps are not retained and it triggers a rebuild

**Comment by nickma82** [comment]
Checked out the repo today (master branch), with the same problem on a RaspberryPI.
Automake version 1.11.6

`autoreconf -vfi` fixed it too.

**Comment by nickma82** [comment]
Shouldn't all the build aggregates (i.e. _Makefile.in aclocal.m4 configure doc/Makefile.in libtool src/Makefile.in_) not being checked in?

S.t. in order to compile everyone would have to issue a standard `./configure` followed by a 'make'

**Comment by 3cky** [comment]
Really I already thinking about transition to cmake for a long time. Will try to find some time to make it done. Also created #22 to track work progress.

**Comment by nickma82** [comment]
close it plz
